### PR TITLE
add nginx authentication support and https redirection

### PR DESCRIPTION
**Pull request by idoshamun**

### CODE REVIEW

**Comment by saltosystems** [comment]
Hi @idosh,

First of all, thanks for your PR!

I'm going to enumerate and discuss all your changes one by one:
* remove unneeded certificate: you're removing the diffie-helman param from the config which is not desired, i'm going to create a new one on each execution.
* add nginx authentication support: your implementation solves authentication for concrete locations which probably solves your use-case but it's not a generic solution. Imagine that I wanna give authentication capabilities for each use case:
  - Server level
  ```
  /lb
    /settings = {
      authentication = true /* this will look for nginx.auth file */
    }
  ```
  - Listener level
  ```
  /lb
    /lisa.contoso.com
      /listeners
        /ls1 = {
          protocol: http,
          address: 0.0.0.0:80,
          settings: {
            authentication: true /* this will look for lisa.contoso.com.auth */
          }
        }
  ```
  - Location level
  ```
  /lb
    /lisa.contoso.com
      /locations
        /loc1 = {
          path: /,
          upstream: "upstreamName"
          settings: {
            authentication: true /* this will look for lisa.contoso.com.upstreamName.auth */
          }
        }
  ```
I want to think more about it because I feel like I'm overcomplicating everything which is what I want to avoid. Take a look to vulcand which creates a middleware concept, maybe something like that should solve these kind of things...
* add https redirection: this should be materialized in the configuration because maybe you don't want to do an automatic redirection because you want to avoid 'mixed content' issues.
* update nginx configuration: i agree with all changes, i'm going to include them tomorrow :-)

What do you think?

**Comment by glerchundi** [comment]
Hi @idosh,

First of all, thanks for your PR!

I'm going to enumerate and discuss all your changes one by one:
- remove unneeded certificate: you're removing the diffie-helman param from the config which is not desired, i'm going to create a new one on each execution.
- add nginx authentication support: your implementation solves authentication for concrete locations which probably solves your use-case but it's not a generic solution. Imagine that I wanna give authentication capabilities for each use case:
  - Server level
  
  ```
  /lb
    /settings = {
      authentication = true /* this will look for nginx.auth file */
    }
  ```
  - Listener level
  
  ```
  /lb
    /lisa.contoso.com
      /listeners
        /ls1 = {
          protocol: http,
          address: 0.0.0.0:80,
          settings: {
            authentication: true /* this will look for lisa.contoso.com.auth */
          }
        }
  ```
  - Location level
  
  ```
  /lb
    /lisa.contoso.com
      /locations
        /loc1 = {
          path: /,
          upstream: "upstreamName"
          settings: {
            authentication: true /* this will look for lisa.contoso.com.upstreamName.auth */
          }
        }
  ```
  
  I want to think more about it because I feel like I'm overcomplicating everything which is what I want to avoid. Take a look to vulcand which creates a middleware concept, maybe something like that should solve these kind of things...
- add https redirection: this should be materialized in the configuration because maybe you don't want to do an automatic redirection because you want to avoid 'mixed content' issues.
- update nginx configuration: i agree with all changes, i'm going to include them tomorrow :-)

What do you think?

**Comment by idoshamun** [comment]
The only thing troubles me is the authentication support.
I'm not sure you should go generic all the way, you won't get out of it.

**Comment by glerchundi** [comment]
#13 pull request should solve most of your issues except https redirection. I've created a `.nginx` section per each {listener,location} which could include any nginx-specific configuration parameter, for example:

```
/lb
  /hosts
    /lisa.contoso.com
      /listeners
        /ls1 = 
          /.nginx = '{
            "auth_basic": "\"restricted\"",
            "auth_basic_user_file": "/etc/nginx/certs/lisa.contoso.com.htpasswd"
          }'
          /value = '{
            "protocol": "http",
            "address": "0.0.0.0:80"
          }'
      /locations
        /loc1
          /.nginx = '{
            "auth_basic": "off"
          }'
          /value = '{
            "path": "/",
            "upstream": "up1"
          }'
        /loc2 = '{
          "path": "/api/.*",
          "upstream": "up1"
        }'
...
```

There is an already functional nginx image on quay: `quay.io/justcontainers/nginx-loadbalancer:v0.5.0`

**Comment by idoshamun** [comment]
Sounds great, I'll check it out

**Comment by glerchundi** [comment]
@idosh, if this solves at least most of the problems you were facing (except http redir. which I already defined as a new issues: #16), close this pull request!

great to see people finding this useful :-)

**Pull request closed without merging**
